# -*- coding: utf-8 -*-
"""28Jan-Class-No-II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGSvVGndftiL2dPHoQa0CE8mm5kslt8Z

ASSIGNMENT CLASS 2
"""

first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")

first_name = first_name.upper()
last_name = last_name.lower()

total_letters = len(first_name) + len(last_name)
print(f"First name (upper): {first_name}")
print(f"Last name (lower): {last_name}")
print("Sum of letters in your first and last name:", total_letters)

print("Calculate the area of following shapes:")
print("1. Circle")
print("2. Rectangle")
print("3. Square")
print("4. Triangle")

shape = input("Enter the shape you want to calculate the area of: ")
print(f"\nFinding the Area of {shape}:")

# Area of Circle
radius = float(input("\nEnter the radius of the circle: "))
area_of_circle = 3.14 * radius ** 2
print(f"\nThe area of the circle is: {area_of_circle} metre_squared.\n")


# Area of Rectangle
print("\nFind area of Rectangle")
length = float(input("Enter length: "))
width = float(input("Enter width: "))
area = length * width
print(f"\nArea of rectangle is {area}\n")


# Area of Square
print("\nFind area of Square")
side = float(input("Enter side: "))
area = side * side
print(f"\nArea of square is {area}\n")


# Area of Triangle
print("\nFind area of Triangle")
breadth = float(input("Enter breadth: "))
height = float(input("Enter height: "))
area = 0.5 * breadth * height
print(f"\nArea of triangle is {area}\n")

import random

colors = ["red", "blue", "green", "yellow", "orange", "purple"]
index = random.randint(0, len(colors) - 1)

selected_color = colors[index]
password = selected_color[::-1]
print("Selected Color:", selected_color)
print("Generated Password:", password)



